[versions]
kotlin = "1.4.31"

[libraries]
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js", version = "1.4.3" }
chrome = { module = "com.github.AndrewReitz:chrome-extension-kotlin-api", version = "main-SNAPSHOT" }
html = { module = "org.jetbrains.kotlinx:kotlinx-html-js", version = "0.7.2"}

[bundles]
extension = ["coroutines", "chrome"]
